def init_property() -> list:
    HuaWuQue = [
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "等級",
            "offset": [0x4, 0x468],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "生命(當前)",
            "offset": [0x4, 0x494],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "生命(最大)",
            "offset": [0x4, 0x44C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "內力(當前)",
            "offset": [0x4, 0x498],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "內力(最大)",
            "offset": [0x4, 0x450],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "攻擊 1",
            "offset": [0x4, 0x454],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "攻擊 2",
            "offset": [0x4, 0x49C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "防禦 1",
            "offset": [0x4, 0x458],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "防禦 2",
            "offset": [0x4, 0x4A0],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "反應 1",
            "offset": [0x4, 0x460],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "反應 2",
            "offset": [0x4, 0x4A4],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "速度 1",
            "offset": [0x4, 0x45C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "速度 2",
            "offset": [0x4, 0x4A8],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "智力 1",
            "offset": [0x4, 0x464],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "智力 2",
            "offset": [0x4, 0x4AC],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "經驗(當前)",
            "offset": [0x4, 0x470],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "經驗(最大)",
            "offset": [0x4, 0x474],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "精元點數",
            "offset": [0x4, 0x46C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "升級點數剩餘",
            "offset": [0x4, 0x488],
        },
    ]
    JiangXiaoYu = [
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "等級",
            "offset": [0x8, 0x468],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "生命(當前)",
            "offset": [0x8, 0x494],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "生命(最大)",
            "offset": [0x8, 0x44C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "內力(當前)",
            "offset": [0x8, 0x498],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "內力(最大)",
            "offset": [0x8, 0x450],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "攻擊 1",
            "offset": [0x8, 0x454],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "攻擊 2",
            "offset": [0x8, 0x49C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "防禦 1",
            "offset": [0x8, 0x458],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "防禦 2",
            "offset": [0x8, 0x4A0],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "反應 1",
            "offset": [0x8, 0x460],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "反應 2",
            "offset": [0x8, 0x4A4],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "速度 1",
            "offset": [0x8, 0x45C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "速度 2",
            "offset": [0x8, 0x4A8],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "智力 1",
            "offset": [0x8, 0x464],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "智力 2",
            "offset": [0x8, 0x4AC],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "經驗(當前)",
            "offset": [0x8, 0x470],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "經驗(最大)",
            "offset": [0x8, 0x474],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "精元點數",
            "offset": [0x8, 0x46C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "升級點數剩餘",
            "offset": [0x8, 0x488],
        },
    ]
    ZhangJing = [
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "等級",
            "offset": [0x10, 0x468],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "生命(當前)",
            "offset": [0x10, 0x494],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "生命(最大)",
            "offset": [0x10, 0x44C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "內力(當前)",
            "offset": [0x10, 0x498],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "內力(最大)",
            "offset": [0x10, 0x450],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "攻擊 1",
            "offset": [0x10, 0x454],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "攻擊 2",
            "offset": [0x10, 0x49C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "防禦 1",
            "offset": [0x10, 0x458],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "防禦 2",
            "offset": [0x10, 0x4A0],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "反應 1",
            "offset": [0x10, 0x460],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "反應 2",
            "offset": [0x10, 0x4A4],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "速度 1",
            "offset": [0x10, 0x45C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "速度 2",
            "offset": [0x10, 0x4A8],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "智力 1",
            "offset": [0x10, 0x464],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "智力 2",
            "offset": [0x10, 0x4AC],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "經驗(當前)",
            "offset": [0x10, 0x470],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "經驗(最大)",
            "offset": [0x10, 0x474],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "精元點數",
            "offset": [0x10, 0x46C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "升級點數剩餘",
            "offset": [0x10, 0x488],
        },
    ]
    TieXinLan = [
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "等級",
            "offset": [0x14, 0x468],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "生命(當前)",
            "offset": [0x14, 0x494],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "生命(最大)",
            "offset": [0x14, 0x44C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "內力(當前)",
            "offset": [0x14, 0x498],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "內力(最大)",
            "offset": [0x14, 0x450],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "攻擊 1",
            "offset": [0x14, 0x454],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "攻擊 2",
            "offset": [0x14, 0x49C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "防禦 1",
            "offset": [0x14, 0x458],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "防禦 2",
            "offset": [0x14, 0x4A0],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "反應 1",
            "offset": [0x14, 0x460],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "反應 2",
            "offset": [0x14, 0x4A4],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "速度 1",
            "offset": [0x14, 0x45C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "速度 2",
            "offset": [0x14, 0x4A8],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "智力 1",
            "offset": [0x14, 0x464],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "智力 2",
            "offset": [0x14, 0x4AC],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "經驗(當前)",
            "offset": [0x14, 0x470],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "經驗(最大)",
            "offset": [0x14, 0x474],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "精元點數",
            "offset": [0x14, 0x46C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "升級點數剩餘",
            "offset": [0x14, 0x488],
        },
    ]
    HeLu = [
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "等級",
            "offset": [0x18, 0x468],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "生命(當前)",
            "offset": [0x18, 0x494],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "生命(最大)",
            "offset": [0x18, 0x44C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "內力(當前)",
            "offset": [0x18, 0x498],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "內力(最大)",
            "offset": [0x18, 0x450],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "攻擊 1",
            "offset": [0x18, 0x454],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "攻擊 2",
            "offset": [0x18, 0x49C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "防禦 1",
            "offset": [0x18, 0x458],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "防禦 2",
            "offset": [0x18, 0x4A0],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "反應 1",
            "offset": [0x18, 0x460],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "反應 2",
            "offset": [0x18, 0x4A4],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "速度 1",
            "offset": [0x18, 0x45C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "速度 2",
            "offset": [0x18, 0x4A8],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "智力 1",
            "offset": [0x18, 0x464],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "智力 2",
            "offset": [0x18, 0x4AC],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "經驗(當前)",
            "offset": [0x18, 0x470],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "經驗(最大)",
            "offset": [0x18, 0x474],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "精元點數",
            "offset": [0x18, 0x46C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "升級點數剩餘",
            "offset": [0x18, 0x488],
        },
    ]
    HeiZhiZhu = [
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "等級",
            "offset": [0x1C, 0x468],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "生命(當前)",
            "offset": [0x1C, 0x494],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "生命(最大)",
            "offset": [0x1C, 0x44C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "內力(當前)",
            "offset": [0x1C, 0x498],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "內力(最大)",
            "offset": [0x1C, 0x450],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "攻擊 1",
            "offset": [0x1C, 0x454],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "攻擊 2",
            "offset": [0x1C, 0x49C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "防禦 1",
            "offset": [0x1C, 0x458],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "防禦 2",
            "offset": [0x1C, 0x4A0],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "反應 1",
            "offset": [0x1C, 0x460],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "反應 2",
            "offset": [0x1C, 0x4A4],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "速度 1",
            "offset": [0x1C, 0x45C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "速度 2",
            "offset": [0x1C, 0x4A8],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "智力 1",
            "offset": [0x1C, 0x464],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "智力 2",
            "offset": [0x1C, 0x4AC],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "經驗(當前)",
            "offset": [0x1C, 0x470],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "經驗(最大)",
            "offset": [0x1C, 0x474],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "精元點數",
            "offset": [0x1C, 0x46C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "升級點數剩餘",
            "offset": [0x1C, 0x488],
        },
    ]
    XuanYuanSanGuang = [
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "等級",
            "offset": [0x20, 0x468],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "生命(當前)",
            "offset": [0x20, 0x494],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "生命(最大)",
            "offset": [0x20, 0x44C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "內力(當前)",
            "offset": [0x20, 0x498],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "內力(最大)",
            "offset": [0x20, 0x450],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "攻擊 1",
            "offset": [0x20, 0x454],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "攻擊 2",
            "offset": [0x20, 0x49C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "防禦 1",
            "offset": [0x20, 0x458],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "防禦 2",
            "offset": [0x20, 0x4A0],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "反應 1",
            "offset": [0x20, 0x460],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "反應 2",
            "offset": [0x20, 0x4A4],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "速度 1",
            "offset": [0x20, 0x45C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "速度 2",
            "offset": [0x20, 0x4A8],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "智力 1",
            "offset": [0x20, 0x464],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "智力 2",
            "offset": [0x20, 0x4AC],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "經驗(當前)",
            "offset": [0x20, 0x470],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "經驗(最大)",
            "offset": [0x20, 0x474],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "精元點數",
            "offset": [0x20, 0x46C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "升級點數剩餘",
            "offset": [0x20, 0x488],
        },
    ]
    YanNanTian = [
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "等級",
            "offset": [0x28, 0x468],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "生命(當前)",
            "offset": [0x28, 0x494],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "生命(最大)",
            "offset": [0x28, 0x44C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "內力(當前)",
            "offset": [0x28, 0x498],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "內力(最大)",
            "offset": [0x28, 0x450],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "攻擊 1",
            "offset": [0x28, 0x454],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "攻擊 2",
            "offset": [0x28, 0x49C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "防禦 1",
            "offset": [0x28, 0x458],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "防禦 2",
            "offset": [0x28, 0x4A0],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "反應 1",
            "offset": [0x28, 0x460],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "反應 2",
            "offset": [0x28, 0x4A4],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "速度 1",
            "offset": [0x28, 0x45C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "速度 2",
            "offset": [0x28, 0x4A8],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "智力 1",
            "offset": [0x28, 0x464],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "智力 2",
            "offset": [0x28, 0x4AC],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "經驗(當前)",
            "offset": [0x28, 0x470],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "經驗(最大)",
            "offset": [0x28, 0x474],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "精元點數",
            "offset": [0x28, 0x46C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "升級點數剩餘",
            "offset": [0x28, 0x488],
        },
    ]
    LianXing = [
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "等級",
            "offset": [0x2C, 0x468],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "生命(當前)",
            "offset": [0x2C, 0x494],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "生命(最大)",
            "offset": [0x2C, 0x44C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "內力(當前)",
            "offset": [0x2C, 0x498],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "內力(最大)",
            "offset": [0x2C, 0x450],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "攻擊 1",
            "offset": [0x2C, 0x454],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "攻擊 2",
            "offset": [0x2C, 0x49C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "防禦 1",
            "offset": [0x2C, 0x458],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "防禦 2",
            "offset": [0x2C, 0x4A0],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "反應 1",
            "offset": [0x2C, 0x460],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "反應 2",
            "offset": [0x2C, 0x4A4],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "速度 1",
            "offset": [0x2C, 0x45C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "速度 2",
            "offset": [0x2C, 0x4A8],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "智力 1",
            "offset": [0x2C, 0x464],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "智力 2",
            "offset": [0x2C, 0x4AC],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "經驗(當前)",
            "offset": [0x2C, 0x470],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "經驗(最大)",
            "offset": [0x2C, 0x474],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "精元點數",
            "offset": [0x2C, 0x46C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "升級點數剩餘",
            "offset": [0x2C, 0x488],
        },
    ]

    # ================== 錢 ==================
    Qian = [
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "錢",
            "item": "錢",
            "offset": [0x40, 0x0],
        },
    ]

    # ================== 秘笈 ==================
    MiJi = list()
    for idx, val in enumerate(range(0, 356, 4)):
        MiJi.append(
            {
                "activate": 1,
                "game": "TTH2SP.exe",
                "role": "花無缺",
                "cat": "秘笈",
                "item": f"秘笈 {idx + 1}",
                "offset": [0x40, 0x4B4 + val],
            }
        )

    # ================== 藥草 ==================
    YaoCao = list()
    for idx, val in enumerate(range(0, 68, 4)):
        YaoCao.append(
            {
                "activate": 1,
                "game": "TTH2SP.exe",
                "role": "花無缺",
                "cat": "藥草",
                "item": f"藥草 {idx + 1}",
                "offset": [0x40, 0x284 + val],
            }
        )
    for idx, val in enumerate(range(0, 12, 4)):
        YaoCao.append(
            {
                "activate": 1,
                "game": "TTH2SP.exe",
                "role": "花無缺",
                "cat": "藥草",
                "item": f"藥草 {idx + 18}",
                "offset": [0x40, 0x364 + val],
            }
        )

    # ================== 刀 ==================
    Dao = list()
    for idx, val in enumerate(range(0, 128, 4)):
        Dao.append(
            {
                "activate": 1,
                "game": "TTH2SP.exe",
                "role": "花無缺",
                "cat": "刀",
                "item": f"刀 {idx + 1}",
                "offset": [0x40, 0x4 + val],
            }
        )

    # ================== 劍 ==================
    Jian = list()
    for idx, val in enumerate(range(0, 124, 4)):
        Jian.append(
            {
                "activate": 1,
                "game": "TTH2SP.exe",
                "role": "花無缺",
                "cat": "劍",
                "item": f"劍 {idx + 1}",
                "offset": [0x40, 0x88 + val],
            }
        )

    # ================== 鞭 ==================
    Bian = list()
    for idx, val in enumerate(range(0, 52, 4)):
        Bian.append(
            {
                "activate": 1,
                "game": "TTH2SP.exe",
                "role": "花無缺",
                "cat": "鞭",
                "item": f"鞭 {idx + 1}",
                "offset": [0x40, 0x108 + val],
            }
        )

    # ================== 甲 ==================
    Jia = list()
    for idx, val in enumerate(range(0, 228, 4)):
        Jia.append(
            {
                "activate": 1,
                "game": "TTH2SP.exe",
                "role": "花無缺",
                "cat": "甲",
                "item": f"甲 {idx + 1}",
                "offset": [0x40, 0x140 + val],
            }
        )

    # ================== 靴 ==================
    Xue = list()
    for idx, val in enumerate(range(0, 80, 4)):
        Xue.append(
            {
                "activate": 1,
                "game": "TTH2SP.exe",
                "role": "花無缺",
                "cat": "靴",
                "item": f"靴 {idx + 1}",
                "offset": [0x40, 0x234 + val],
            }
        )

    # ================== 弓 ==================
    Gong = list()
    for idx, val in enumerate(range(0, 52, 4)):
        Gong.append(
            {
                "activate": 1,
                "game": "TTH2SP.exe",
                "role": "花無缺",
                "cat": "靴",
                "item": f"靴 {idx + 1}",
                "offset": [0x40, 0x70C + val],
            }
        )

    # ================== 醫療 ==================
    YiLiao = list()
    for idx, val in enumerate(range(0, 148, 4)):
        YiLiao.append(
            {
                "activate": 1,
                "game": "TTH2SP.exe",
                "role": "花無缺",
                "cat": "醫療",
                "item": f"醫療 {idx + 1}",
                "offset": [0x40, 0x2D0 + val],
            }
        )

    # ================== 暗器 ==================
    AnQi = list()
    for idx, val in enumerate(range(0, 40, 4)):
        AnQi.append(
            {
                "activate": 1,
                "game": "TTH2SP.exe",
                "role": "花無缺",
                "cat": "暗器",
                "item": f"暗器 {idx + 1}",
                "offset": [0x40, 0x3EC + val],
            }
        )

    # ================== 道具 ==================
    DaoJu = list()
    for idx, val in enumerate(range(0, 140, 4)):
        DaoJu.append(
            {
                "activate": 1,
                "game": "TTH2SP.exe",
                "role": "花無缺",
                "cat": "道具",
                "item": f"道具 {idx + 1}",
                "offset": [0x40, 0x414 + val],
            }
        )

    # 整理
    result = (
        HuaWuQue
        + JiangXiaoYu
        + ZhangJing
        + TieXinLan
        + HeLu
        + HeiZhiZhu
        + XuanYuanSanGuang
        + YanNanTian
        + LianXing
        + Qian
        + MiJi
        + YaoCao
        + Dao
        + Jian
        + Bian
        + Jia
        + Xue
        + Gong
        + YiLiao
        + AnQi
        + DaoJu
    )
    return result
