def init() -> list:
    HuaWuQue = [
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "等級",
            "offset": [0x4, 0x468],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "生命(當前)",
            "offset": [0x4, 0x494],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "生命(最大)",
            "offset": [0x4, 0x44C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "內力(當前)",
            "offset": [0x4, 0x498],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "內力(最大)",
            "offset": [0x4, 0x450],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "攻擊 1",
            "offset": [0x4, 0x454],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "攻擊 2",
            "offset": [0x4, 0x49C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "防禦 1",
            "offset": [0x4, 0x458],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "防禦 2",
            "offset": [0x4, 0x4A0],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "反應 1",
            "offset": [0x4, 0x460],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "反應 2",
            "offset": [0x4, 0x4A4],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "速度 1",
            "offset": [0x4, 0x45C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "速度 2",
            "offset": [0x4, 0x4A8],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "智力 1",
            "offset": [0x4, 0x464],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "智力 2",
            "offset": [0x4, 0x4AC],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "經驗(當前)",
            "offset": [0x4, 0x470],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "經驗(最大)",
            "offset": [0x4, 0x474],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "精元點數",
            "offset": [0x4, 0x46C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "花無缺",
            "item": "升級點數剩餘",
            "offset": [0x4, 0x488],
        },
    ]
    JiangXiaoYu = [
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "等級",
            "offset": [0x8, 0x468],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "生命(當前)",
            "offset": [0x8, 0x494],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "生命(最大)",
            "offset": [0x8, 0x44C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "內力(當前)",
            "offset": [0x8, 0x498],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "內力(最大)",
            "offset": [0x8, 0x450],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "攻擊 1",
            "offset": [0x8, 0x454],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "攻擊 2",
            "offset": [0x8, 0x49C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "防禦 1",
            "offset": [0x8, 0x458],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "防禦 2",
            "offset": [0x8, 0x4A0],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "反應 1",
            "offset": [0x8, 0x460],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "反應 2",
            "offset": [0x8, 0x4A4],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "速度 1",
            "offset": [0x8, 0x45C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "速度 2",
            "offset": [0x8, 0x4A8],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "智力 1",
            "offset": [0x8, 0x464],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "智力 2",
            "offset": [0x8, 0x4AC],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "經驗(當前)",
            "offset": [0x8, 0x470],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "經驗(最大)",
            "offset": [0x8, 0x474],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "精元點數",
            "offset": [0x8, 0x46C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "江小魚",
            "item": "升級點數剩餘",
            "offset": [0x8, 0x488],
        },
    ]
    ZhangJing = [
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "等級",
            "offset": [0x10, 0x468],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "生命(當前)",
            "offset": [0x10, 0x494],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "生命(最大)",
            "offset": [0x10, 0x44C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "內力(當前)",
            "offset": [0x10, 0x498],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "內力(最大)",
            "offset": [0x10, 0x450],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "攻擊 1",
            "offset": [0x10, 0x454],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "攻擊 2",
            "offset": [0x10, 0x49C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "防禦 1",
            "offset": [0x10, 0x458],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "防禦 2",
            "offset": [0x10, 0x4A0],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "反應 1",
            "offset": [0x10, 0x460],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "反應 2",
            "offset": [0x10, 0x4A4],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "速度 1",
            "offset": [0x10, 0x45C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "速度 2",
            "offset": [0x10, 0x4A8],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "智力 1",
            "offset": [0x10, 0x464],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "智力 2",
            "offset": [0x10, 0x4AC],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "經驗(當前)",
            "offset": [0x10, 0x470],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "經驗(最大)",
            "offset": [0x10, 0x474],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "精元點數",
            "offset": [0x10, 0x46C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "張菁",
            "item": "升級點數剩餘",
            "offset": [0x10, 0x488],
        },
    ]
    TieXinLan = [
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "等級",
            "offset": [0x14, 0x468],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "生命(當前)",
            "offset": [0x14, 0x494],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "生命(最大)",
            "offset": [0x14, 0x44C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "內力(當前)",
            "offset": [0x14, 0x498],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "內力(最大)",
            "offset": [0x14, 0x450],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "攻擊 1",
            "offset": [0x14, 0x454],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "攻擊 2",
            "offset": [0x14, 0x49C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "防禦 1",
            "offset": [0x14, 0x458],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "防禦 2",
            "offset": [0x14, 0x4A0],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "反應 1",
            "offset": [0x14, 0x460],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "反應 2",
            "offset": [0x14, 0x4A4],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "速度 1",
            "offset": [0x14, 0x45C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "速度 2",
            "offset": [0x14, 0x4A8],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "智力 1",
            "offset": [0x14, 0x464],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "智力 2",
            "offset": [0x14, 0x4AC],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "經驗(當前)",
            "offset": [0x14, 0x470],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "經驗(最大)",
            "offset": [0x14, 0x474],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "精元點數",
            "offset": [0x14, 0x46C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "鐵心蘭",
            "item": "升級點數剩餘",
            "offset": [0x14, 0x488],
        },
    ]
    HeLu = [
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "等級",
            "offset": [0x18, 0x468],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "生命(當前)",
            "offset": [0x18, 0x494],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "生命(最大)",
            "offset": [0x18, 0x44C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "內力(當前)",
            "offset": [0x18, 0x498],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "內力(最大)",
            "offset": [0x18, 0x450],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "攻擊 1",
            "offset": [0x18, 0x454],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "攻擊 2",
            "offset": [0x18, 0x49C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "防禦 1",
            "offset": [0x18, 0x458],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "防禦 2",
            "offset": [0x18, 0x4A0],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "反應 1",
            "offset": [0x18, 0x460],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "反應 2",
            "offset": [0x18, 0x4A4],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "速度 1",
            "offset": [0x18, 0x45C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "速度 2",
            "offset": [0x18, 0x4A8],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "智力 1",
            "offset": [0x18, 0x464],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "智力 2",
            "offset": [0x18, 0x4AC],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "經驗(當前)",
            "offset": [0x18, 0x470],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "經驗(最大)",
            "offset": [0x18, 0x474],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "精元點數",
            "offset": [0x18, 0x46C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "荷露",
            "item": "升級點數剩餘",
            "offset": [0x18, 0x488],
        },
    ]
    HeiZhiZhu = [
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "等級",
            "offset": [0x1C, 0x468],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "生命(當前)",
            "offset": [0x1C, 0x494],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "生命(最大)",
            "offset": [0x1C, 0x44C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "內力(當前)",
            "offset": [0x1C, 0x498],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "內力(最大)",
            "offset": [0x1C, 0x450],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "攻擊 1",
            "offset": [0x1C, 0x454],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "攻擊 2",
            "offset": [0x1C, 0x49C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "防禦 1",
            "offset": [0x1C, 0x458],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "防禦 2",
            "offset": [0x1C, 0x4A0],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "反應 1",
            "offset": [0x1C, 0x460],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "反應 2",
            "offset": [0x1C, 0x4A4],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "速度 1",
            "offset": [0x1C, 0x45C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "速度 2",
            "offset": [0x1C, 0x4A8],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "智力 1",
            "offset": [0x1C, 0x464],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "智力 2",
            "offset": [0x1C, 0x4AC],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "經驗(當前)",
            "offset": [0x1C, 0x470],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "經驗(最大)",
            "offset": [0x1C, 0x474],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "精元點數",
            "offset": [0x1C, 0x46C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "黑蜘蛛",
            "item": "升級點數剩餘",
            "offset": [0x1C, 0x488],
        },
    ]
    XuanYuanSanGuang = [
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "等級",
            "offset": [0x20, 0x468],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "生命(當前)",
            "offset": [0x20, 0x494],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "生命(最大)",
            "offset": [0x20, 0x44C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "內力(當前)",
            "offset": [0x20, 0x498],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "內力(最大)",
            "offset": [0x20, 0x450],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "攻擊 1",
            "offset": [0x20, 0x454],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "攻擊 2",
            "offset": [0x20, 0x49C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "防禦 1",
            "offset": [0x20, 0x458],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "防禦 2",
            "offset": [0x20, 0x4A0],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "反應 1",
            "offset": [0x20, 0x460],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "反應 2",
            "offset": [0x20, 0x4A4],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "速度 1",
            "offset": [0x20, 0x45C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "速度 2",
            "offset": [0x20, 0x4A8],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "智力 1",
            "offset": [0x20, 0x464],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "智力 2",
            "offset": [0x20, 0x4AC],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "經驗(當前)",
            "offset": [0x20, 0x470],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "經驗(最大)",
            "offset": [0x20, 0x474],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "精元點數",
            "offset": [0x20, 0x46C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "軒轅三光",
            "item": "升級點數剩餘",
            "offset": [0x20, 0x488],
        },
    ]
    YanNanTian = [
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "等級",
            "offset": [0x28, 0x468],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "生命(當前)",
            "offset": [0x28, 0x494],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "生命(最大)",
            "offset": [0x28, 0x44C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "內力(當前)",
            "offset": [0x28, 0x498],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "內力(最大)",
            "offset": [0x28, 0x450],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "攻擊 1",
            "offset": [0x28, 0x454],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "攻擊 2",
            "offset": [0x28, 0x49C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "防禦 1",
            "offset": [0x28, 0x458],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "防禦 2",
            "offset": [0x28, 0x4A0],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "反應 1",
            "offset": [0x28, 0x460],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "反應 2",
            "offset": [0x28, 0x4A4],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "速度 1",
            "offset": [0x28, 0x45C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "速度 2",
            "offset": [0x28, 0x4A8],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "智力 1",
            "offset": [0x28, 0x464],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "智力 2",
            "offset": [0x28, 0x4AC],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "經驗(當前)",
            "offset": [0x28, 0x470],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "經驗(最大)",
            "offset": [0x28, 0x474],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "精元點數",
            "offset": [0x28, 0x46C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "燕南天",
            "item": "升級點數剩餘",
            "offset": [0x28, 0x488],
        },
    ]
    LianXing = [
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "等級",
            "offset": [0x2C, 0x468],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "生命(當前)",
            "offset": [0x2C, 0x494],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "生命(最大)",
            "offset": [0x2C, 0x44C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "內力(當前)",
            "offset": [0x2C, 0x498],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "內力(最大)",
            "offset": [0x2C, 0x450],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "攻擊 1",
            "offset": [0x2C, 0x454],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "攻擊 2",
            "offset": [0x2C, 0x49C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "防禦 1",
            "offset": [0x2C, 0x458],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "防禦 2",
            "offset": [0x2C, 0x4A0],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "反應 1",
            "offset": [0x2C, 0x460],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "反應 2",
            "offset": [0x2C, 0x4A4],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "速度 1",
            "offset": [0x2C, 0x45C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "速度 2",
            "offset": [0x2C, 0x4A8],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "智力 1",
            "offset": [0x2C, 0x464],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "智力 2",
            "offset": [0x2C, 0x4AC],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "經驗(當前)",
            "offset": [0x2C, 0x470],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "經驗(最大)",
            "offset": [0x2C, 0x474],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "精元點數",
            "offset": [0x2C, 0x46C],
        },
        {
            "activate": 1,
            "game": "TTH2SP.exe",
            "role": "花無缺",
            "cat": "憐星",
            "item": "升級點數剩餘",
            "offset": [0x2C, 0x488],
        },
    ]
    result = (
        HuaWuQue
        + JiangXiaoYu
        + ZhangJing
        + TieXinLan
        + HeLu
        + HeiZhiZhu
        + XuanYuanSanGuang
        + YanNanTian
        + LianXing
    )
    return result
